# Generated by Django 4.2.2 on 2024-09-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_autor"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.CharField(
                choices=[("ACTIVE", "активный"), ("INACTIVE", "неактивный")],
                default="INACTIVE",
                max_length=20,
                verbose_name="публикация",
            ),
        ),
    ]
