# Generated by Django 4.2.2 on 2024-09-15 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["id"],
                "permissions": [
                    ("can_edit_is_published", "can edit is_published"),
                    ("can_edit_description", "can edit description"),
                    ("can_edit_category", "can edir category"),
                ],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
